uploads = []
generated = []

[[outputs]]
id = "a3UpdQZgKztdpeqoQhQ9X"
uri = "file://sot-treasure-standalone.tar.gz"
type = "unspecified"
title = "Sea of Thieves Treasure Guide — standalone (185 items)"
